name: Build Tests For Windows

on:
  release:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  QT_VERSION: 6.5.3

jobs:
  win-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        arch: [x64, arm64]
        include:
          - arch: x64
            qt-arch: msvc2019_64
          - arch: arm64
            qt-arch: msvc2019_arm64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/code
          submodules: recursive

      - name: Install Qt (Host)
        uses: jurplel/install-qt-action@v3
        if: ${{ matrix.arch != 'x64' }}
        with:
          version: ${{ env.QT_VERSION }}
          modules: 'qt5compat'
          arch: 'win64_msvc2019_64'
          dir: ${{ github.workspace }}
          cache: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          modules: 'qt5compat'
          arch: win64_${{ matrix.qt-arch }}
          dir: ${{ github.workspace }}
          cache: true

      - name: Cache Dependencies
        id: deps-cache
        uses: actions/cache@v3
        with:
          key: deps-${{ hashFiles('code/win_build.ps1') }}
          path: "deps"

      - name: Prepare Dependencies
        if: steps.deps-cache.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          & "${{ github.workspace }}/code/win_build.ps1" "${{ github.workspace }}/code" ${{ matrix.arch }} deps

      - name: Configure
        shell: pwsh
        run: |
          & "${{ github.workspace }}/code/win_build.ps1" "${{ github.workspace }}/code" ${{ matrix.arch }} configure
        env:
            QT_ROOT_DIR: ${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/${{ matrix.qt-arch }}
            QT_HOST_PATH: ${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/msvc2019_64

      - name: Build
        shell: pwsh
        run: |
          & "${{ github.workspace }}/code/win_build.ps1" "${{ github.workspace }}/code" ${{ matrix.arch }} build

      - name: Deploy
        shell: pwsh
        run: |
          & "${{ github.workspace }}/code/win_build.ps1" "${{ github.workspace }}/code" ${{ matrix.arch }} deploy
        env:
            QT_ROOT_DIR: ${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/${{ matrix.qt-arch }}

      - name: Upload Build Directory
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-build
          path: "build"
          compression-level: 9
          if-no-files-found: warn

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-setup
          path: "InputLeapSetup.exe"
          compression-level: 9
          if-no-files-found: warn
