name: Build Tests For Windows

on:
  release:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      build_release:
        description: 'Build Release binaries'
        required: false
        type: boolean

# Set the build type here
env:
  B_BUILD_TYPE: ${{ (inputs.build_release || github.event_name == 'release') && 'Release' || 'Debug' }}

jobs:
  win-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]

    steps:
      - uses: actions/checkout@v4
        with:
          path: input-leap
          submodules: recursive

      - name: Download Bonjour SDK-like
        id: bonjour
        run: |
          $ErrorActionPreference = "Stop"
          New-Item -Force -ItemType Directory -Path .\deps

          Invoke-WebRequest 'https://github.com/nelsonjchen/mDNSResponder/releases/download/v2019.05.08.1/x64_RelWithDebInfo.zip' -OutFile 'deps\BonjourSDKLike.zip' ;
          Expand-Archive .\deps\BonjourSDKLike.zip -DestinationPath .\deps\BonjourSDKLike
          Remove-Item deps\BonjourSDKLike.zip

          "path=$env:GITHUB_WORKSPACE\deps\BonjourSDKLike" >> $env:GITHUB_OUTPUT

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15
          cache: true
          cache-key-prefix: windows-${{matrix.os}}-Qt${{matrix.qt-version}}

      - name: Configure build system
        # NB. use cmd here to set variables from VsDevCmd.bat
        shell: cmd
        run: |
          call "%VS_PATH%\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=amd64

          cmake -S input-leap -B build -G "%CMAKE_GEN%" -A x64 -D CMAKE_BUILD_TYPE=%B_BUILD_TYPE% ^
            -DDNSSD_LIB="%BONJOUR_SDK_HOME%\Lib\x64\dnssd.lib" -D CMAKE_INSTALL_PREFIX=input-leap-install
        env:
          VS_PATH: ${{ matrix.os == 'windows-2019' && '%ProgramFiles(x86)%\Microsoft Visual Studio\2019' || '%ProgramFiles%\Microsoft Visual Studio\2022' }}
          CMAKE_GEN: ${{ matrix.os == 'windows-2019' && 'Visual Studio 16 2019' || 'Visual Studio 17 2022' }}
          BONJOUR_SDK_HOME: ${{ steps.bonjour.outputs.path }}

      - name: Run build system
        run: |
          cmake --build build --config $env:B_BUILD_TYPE --target install

      - name: Copy supporting binaries
        run: |
          copy input-leap\ext\openssl\windows\x64\bin\*.dll input-leap-install\

      - name: Archive Completed Build Directory
        uses: vimtor/action-zip@v1
        with:
          files: input-leap-install
          dest: ${{ env.B_BUILD_TYPE }}.zip

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ env.B_BUILD_TYPE }}
          path: ${{ env.B_BUILD_TYPE }}.zip
          if-no-files-found: warn

      # Only build & upload installer for release builds on windows-2022
      - name: Build the Installer
        if: matrix.os == 'windows-2022' && env.B_BUILD_TYPE == 'Release'
        run: |
          & "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe" /Qp .\build\installer-inno\input-leap.iss

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-2022' && env.B_BUILD_TYPE == 'Release'
        with:
          name: windows-installer
          path: .\build\installer-inno\bin
          if-no-files-found: error
